// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OutTheGC.Data;

#nullable disable

namespace OutTheGC.Migrations
{
    [DbContext(typeof(OutTheGCDbContext))]
    [Migration("20241213022631_AddedStatusToTripInvitation")]
    partial class AddedStatusToTripInvitation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OutTheGC.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Duration")
                        .HasColumnType("numeric");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.Property<bool>("isArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("175a8012-6200-4180-915b-f3e4d604923d"),
                            CategoryId = new Guid("72ff3052-5d20-4996-afec-a837d4df2904"),
                            Cost = 300m,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 8.5m,
                            Location = "Maldives Beach",
                            Notes = "Spend a relaxing day on the beach, soaking in the sun and enjoying the ocean breeze.",
                            Title = "Beach Relaxation",
                            TripId = new Guid("6f927882-1196-4d72-917d-972c6de3f1b4"),
                            UpdatedAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("0eaed767-eecd-4d19-a853-9da895e78057"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("4a7cb92b-2b6a-4316-8bb0-402497c47bdb"),
                            CategoryId = new Guid("a143452f-7b59-4082-8bfa-44faa0d963ed"),
                            Cost = 200m,
                            CreatedAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 4.0m,
                            Location = "Maldives Coral Reef",
                            Notes = "Snorkeling in crystal clear waters, exploring coral reefs and marine life.",
                            Title = "Underwater Adventure",
                            TripId = new Guid("6f927882-1196-4d72-917d-972c6de3f1b4"),
                            UpdatedAt = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("0eaed767-eecd-4d19-a853-9da895e78057"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("8d69e4e8-62b1-465d-bfc7-1a94c3d07a71"),
                            CategoryId = new Guid("48876876-6725-4225-9ae4-0279e87ce888"),
                            Cost = 150m,
                            CreatedAt = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 6.0m,
                            Location = "Maldives Islands",
                            Notes = "A day trip to visit nearby islands, enjoy different beaches, and local markets.",
                            Title = "Island Hopping",
                            TripId = new Guid("6f927882-1196-4d72-917d-972c6de3f1b4"),
                            UpdatedAt = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("0eaed767-eecd-4d19-a853-9da895e78057"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("d7e309b1-dde9-48f5-99b5-7d3c6f153032"),
                            CategoryId = new Guid("27b9d332-04d0-4c7e-8196-ef38fb4779cc"),
                            Cost = 400m,
                            CreatedAt = new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 6.0m,
                            Location = "Zermatt Ski Resort",
                            Notes = "Hit the slopes for a thrilling day of skiing on the Swiss Alps.",
                            Title = "Skiing Adventure",
                            TripId = new Guid("0eb66928-c2b0-4eea-9e4a-f7363fc98778"),
                            UpdatedAt = new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("a3c9c52c-038f-4b3e-a9bc-26496fcbfa0b"),
                            CategoryId = new Guid("a143452f-7b59-4082-8bfa-44faa0d963ed"),
                            Cost = 100m,
                            CreatedAt = new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 5.5m,
                            Location = "Swiss Alps Trails",
                            Notes = "A day hike through the picturesque alpine meadows and rugged terrain.",
                            Title = "Alpine Hiking",
                            TripId = new Guid("0eb66928-c2b0-4eea-9e4a-f7363fc98778"),
                            UpdatedAt = new DateTime(2023, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("b8d3c7d2-8a8e-45d0-8b1a-cbc32bc3b53d"),
                            CategoryId = new Guid("48876876-6725-4225-9ae4-0279e87ce888"),
                            Cost = 120m,
                            CreatedAt = new DateTime(2023, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 2.0m,
                            Location = "Matterhorn Restaurant",
                            Notes = "Enjoy a traditional Swiss meal at a mountaintop restaurant.",
                            Title = "Alpine Dining",
                            TripId = new Guid("0eb66928-c2b0-4eea-9e4a-f7363fc98778"),
                            UpdatedAt = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("ff8f6c32-8e22-4a3c-8d8a-2f1e5b557477"),
                            CategoryId = new Guid("a143452f-7b59-4082-8bfa-44faa0d963ed"),
                            Cost = 200m,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 7.0m,
                            Location = "Yosemite National Park",
                            Notes = "Visit several national parks in the western U.S. on a scenic road trip.",
                            Title = "National Park Tour",
                            TripId = new Guid("4da6ceb3-2c4d-475f-9afd-3eecd34d1523"),
                            UpdatedAt = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("67a99b92-3485-4d39-8bce-33fe4fccfc85"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("bfa47491-e758-4330-bc10-2e60d9a3479d"),
                            CategoryId = new Guid("72ff3052-5d20-4996-afec-a837d4df2904"),
                            Cost = 80m,
                            CreatedAt = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 3.5m,
                            Location = "Big Sur, California",
                            Notes = "A leisurely drive along the Pacific Coast Highway to watch the sunset.",
                            Title = "Sunset Drive",
                            TripId = new Guid("4da6ceb3-2c4d-475f-9afd-3eecd34d1523"),
                            UpdatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("67a99b92-3485-4d39-8bce-33fe4fccfc85"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("d7f9d8ed-4f65-4859-a837-d4a512bf7a6b"),
                            CategoryId = new Guid("48876876-6725-4225-9ae4-0279e87ce888"),
                            Cost = 40m,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 1.5m,
                            Location = "Route 66 Diner",
                            Notes = "Stop at a famous American diner for a classic meal during the road trip.",
                            Title = "Local Diner Stop",
                            TripId = new Guid("4da6ceb3-2c4d-475f-9afd-3eecd34d1523"),
                            UpdatedAt = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("67a99b92-3485-4d39-8bce-33fe4fccfc85"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("f2d85352-0c93-4f58-9739-4e0d63ca90d1"),
                            CategoryId = new Guid("a0254d5f-f540-44df-908b-d33d7c0da285"),
                            Cost = 50m,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 3.0m,
                            Location = "National History Museum",
                            Notes = "Explore the rich history of the region with a guided tour through the local museum.",
                            Title = "Museum Tour",
                            TripId = new Guid("de59cf42-eb57-4045-b7bc-a578db398ad2"),
                            UpdatedAt = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("59c5b94d-8015-48cd-bd86-0dbe486c4719"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("343f58ed-97d1-4324-b231-71e7a3d577e5"),
                            CategoryId = new Guid("a143452f-7b59-4082-8bfa-44faa0d963ed"),
                            Cost = 75m,
                            CreatedAt = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 2.0m,
                            Location = "Cultural Center Theatre",
                            Notes = "Attend an evening performance of traditional local dances and music.",
                            Title = "Cultural Dance Show",
                            TripId = new Guid("de59cf42-eb57-4045-b7bc-a578db398ad2"),
                            UpdatedAt = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("59c5b94d-8015-48cd-bd86-0dbe486c4719"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("da699d06-56b7-4fbd-89b1-b24fdf9b7ab2"),
                            CategoryId = new Guid("a0254d5f-f540-44df-908b-d33d7c0da285"),
                            Cost = 40m,
                            CreatedAt = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 4.0m,
                            Location = "Old Town District",
                            Notes = "Take a guided walking tour of the city's most iconic landmarks.",
                            Title = "Historic Walking Tour",
                            TripId = new Guid("de59cf42-eb57-4045-b7bc-a578db398ad2"),
                            UpdatedAt = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("59c5b94d-8015-48cd-bd86-0dbe486c4719"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("64f3cda1-70cf-4b52-99b2-d9c60a5b5898"),
                            CategoryId = new Guid("72ff3052-5d20-4996-afec-a837d4df2904"),
                            Cost = 150m,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 8.0m,
                            Location = "Paradise Beach",
                            Notes = "Spend a day on the pristine beach, enjoying the sun and clear blue waters.",
                            Title = "Beach Day",
                            TripId = new Guid("172d5607-5dbd-4361-bf3f-fa76bfb84f70"),
                            UpdatedAt = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("24fda663-5bf9-4e0d-8efd-111ae512dff5"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("9b0ecf93-c42d-4c45-9ecb-85b8fe7e2d7c"),
                            CategoryId = new Guid("48876876-6725-4225-9ae4-0279e87ce888"),
                            Cost = 70m,
                            CreatedAt = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 2.5m,
                            Location = "Tropical Bar",
                            Notes = "Savor the best tropical cocktails and exotic juices.",
                            Title = "Tropical Drinks Tasting",
                            TripId = new Guid("172d5607-5dbd-4361-bf3f-fa76bfb84f70"),
                            UpdatedAt = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("92d62312-4397-4c9d-9172-2c8a53e8c6a4"),
                            CategoryId = new Guid("a143452f-7b59-4082-8bfa-44faa0d963ed"),
                            Cost = 120m,
                            CreatedAt = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 4.0m,
                            Location = "Coral Reef Bay",
                            Notes = "Explore the underwater world, discovering vibrant marine life.",
                            Title = "Snorkeling Expedition",
                            TripId = new Guid("172d5607-5dbd-4361-bf3f-fa76bfb84f70"),
                            UpdatedAt = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("24fda663-5bf9-4e0d-8efd-111ae512dff5"),
                            WebsiteUrl = "",
                            isArchived = false,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("OutTheGC.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Default")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a143452f-7b59-4082-8bfa-44faa0d963ed"),
                            Default = true,
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = new Guid("48876876-6725-4225-9ae4-0279e87ce888"),
                            Default = true,
                            Name = "Food & Drinks"
                        },
                        new
                        {
                            Id = new Guid("a0254d5f-f540-44df-908b-d33d7c0da285"),
                            Default = true,
                            Name = "Tours"
                        },
                        new
                        {
                            Id = new Guid("27b9d332-04d0-4c7e-8196-ef38fb4779cc"),
                            Default = true,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("72ff3052-5d20-4996-afec-a837d4df2904"),
                            Default = true,
                            Name = "Relaxation & Wellness"
                        },
                        new
                        {
                            Id = new Guid("973d6c63-ad42-475d-97bd-4197f484ad2a"),
                            Default = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("OutTheGC.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae426b06-094a-49dd-9a86-c5d8e0d8411c"),
                            ActivityId = new Guid("175a8012-6200-4180-915b-f3e4d604923d"),
                            Content = "The beach day sounds so relaxing! Can’t wait to enjoy the sun and sea breeze.",
                            CreatedAt = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("0eaed767-eecd-4d19-a853-9da895e78057")
                        },
                        new
                        {
                            Id = new Guid("69f6738e-ddc1-47d6-b726-1ca8ecd54545"),
                            ActivityId = new Guid("4a7cb92b-2b6a-4316-8bb0-402497c47bdb"),
                            Content = "The underwater adventure is a must-try! The reefs look amazing.",
                            CreatedAt = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("0eaed767-eecd-4d19-a853-9da895e78057")
                        },
                        new
                        {
                            Id = new Guid("cc78771f-bace-48d1-b7db-0ce895e7d6ff"),
                            ActivityId = new Guid("8d69e4e8-62b1-465d-bfc7-1a94c3d07a71"),
                            Content = "Island hopping will be such a fun way to explore the Maldives!",
                            CreatedAt = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("0eaed767-eecd-4d19-a853-9da895e78057")
                        },
                        new
                        {
                            Id = new Guid("e42e4412-13cb-45ee-8276-687e7d4071fa"),
                            ActivityId = new Guid("d7e309b1-dde9-48f5-99b5-7d3c6f153032"),
                            Content = "Skiing in the Alps is a dream come true! Can’t wait for this adventure.",
                            CreatedAt = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc")
                        },
                        new
                        {
                            Id = new Guid("56c91246-7bed-4839-80c1-26b9961fb741"),
                            ActivityId = new Guid("a3c9c52c-038f-4b3e-a9bc-26496fcbfa0b"),
                            Content = "I’m excited for the hiking trip. The views are going to be breathtaking!",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc")
                        },
                        new
                        {
                            Id = new Guid("57a6ffe1-fe80-4e37-9efa-12015440cbdc"),
                            ActivityId = new Guid("b8d3c7d2-8a8e-45d0-8b1a-cbc32bc3b53d"),
                            Content = "Alpine dining sounds so cozy. Can’t wait to try the Swiss specialties.",
                            CreatedAt = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc")
                        },
                        new
                        {
                            Id = new Guid("c62a97ba-d224-477a-9b6a-f2b051141618"),
                            ActivityId = new Guid("ff8f6c32-8e22-4a3c-8d8a-2f1e5b557477"),
                            Content = "The national park tour will be such a scenic experience. Looking forward to it!",
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("67a99b92-3485-4d39-8bce-33fe4fccfc85")
                        },
                        new
                        {
                            Id = new Guid("ef3a9d07-082b-4bc2-a340-80a37f98f392"),
                            ActivityId = new Guid("bfa47491-e758-4330-bc10-2e60d9a3479d"),
                            Content = "A sunset drive along the coast sounds like the perfect way to relax.",
                            CreatedAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("67a99b92-3485-4d39-8bce-33fe4fccfc85")
                        },
                        new
                        {
                            Id = new Guid("bbc4ed5b-535f-4e9b-ae0b-1b3e42596aef"),
                            ActivityId = new Guid("d7f9d8ed-4f65-4859-a837-d4a512bf7a6b"),
                            Content = "Looking forward to the classic diner experience on Route 66!",
                            CreatedAt = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("67a99b92-3485-4d39-8bce-33fe4fccfc85")
                        },
                        new
                        {
                            Id = new Guid("2d32cfe7-d537-4264-b2be-022bcb71e9aa"),
                            ActivityId = new Guid("f2d85352-0c93-4f58-9739-4e0d63ca90d1"),
                            Content = "I’ve always wanted to visit this museum. The history here is so rich!",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("59c5b94d-8015-48cd-bd86-0dbe486c4719")
                        },
                        new
                        {
                            Id = new Guid("6a6396a5-bd09-4266-ab64-d82ea72ac757"),
                            ActivityId = new Guid("343f58ed-97d1-4324-b231-71e7a3d577e5"),
                            Content = "The cultural dance show will be such a treat. I love traditional performances.",
                            CreatedAt = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("59c5b94d-8015-48cd-bd86-0dbe486c4719")
                        },
                        new
                        {
                            Id = new Guid("5eaaf086-621e-4ec5-9471-958f0c975836"),
                            ActivityId = new Guid("da699d06-56b7-4fbd-89b1-b24fdf9b7ab2"),
                            Content = "Exploring the old town will be such a charming experience. Can’t wait!",
                            CreatedAt = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("59c5b94d-8015-48cd-bd86-0dbe486c4719")
                        },
                        new
                        {
                            Id = new Guid("f5be65e2-5d85-48a9-a9f4-6a6aa631d942"),
                            ActivityId = new Guid("64f3cda1-70cf-4b52-99b2-d9c60a5b5898"),
                            Content = "Beach day with blue waters and sun? Yes, please!",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("24fda663-5bf9-4e0d-8efd-111ae512dff5")
                        },
                        new
                        {
                            Id = new Guid("c8a0970c-943a-4230-909f-038723c75bc1"),
                            ActivityId = new Guid("9b0ecf93-c42d-4c45-9ecb-85b8fe7e2d7c"),
                            Content = "Tasting tropical drinks will be a refreshing break. Can’t wait!",
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("24fda663-5bf9-4e0d-8efd-111ae512dff5")
                        },
                        new
                        {
                            Id = new Guid("a829b201-04e8-4d66-8b1d-726f6438373f"),
                            ActivityId = new Guid("92d62312-4397-4c9d-9172-2c8a53e8c6a4"),
                            Content = "Snorkeling at Coral Reef Bay will be a highlight of the trip for sure!",
                            CreatedAt = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("24fda663-5bf9-4e0d-8efd-111ae512dff5")
                        });
                });

            modelBuilder.Entity("OutTheGC.Models.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f927882-1196-4d72-917d-972c6de3f1b4"),
                            Budget = 3500.00m,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Maldives",
                            EndDate = new DateTime(2024, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https =//example.com/images/maldives.jpg",
                            Notes = "A relaxing trip to the beach to unwind and explore new places.",
                            StartDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Planned",
                            Title = "Summer Getaway",
                            UpdatedAt = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("0eaed767-eecd-4d19-a853-9da895e78057")
                        },
                        new
                        {
                            Id = new Guid("0eb66928-c2b0-4eea-9e4a-f7363fc98778"),
                            Budget = 4000.00m,
                            CreatedAt = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Switzerland",
                            EndDate = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/images/alps.jpg",
                            Notes = "An action-packed trip to the Swiss Alps for skiing and hiking.",
                            StartDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed",
                            Title = "Adventure in the Alps",
                            UpdatedAt = new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc")
                        },
                        new
                        {
                            Id = new Guid("4da6ceb3-2c4d-475f-9afd-3eecd34d1523"),
                            Budget = 2500.00m,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "USA",
                            EndDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/images/roadtrip.jpg",
                            Notes = "A long road trip across the United States visiting national parks.",
                            StartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Planned",
                            Title = "Road Trip USA",
                            UpdatedAt = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("67a99b92-3485-4d39-8bce-33fe4fccfc85")
                        },
                        new
                        {
                            Id = new Guid("de59cf42-eb57-4045-b7bc-a578db398ad2"),
                            Budget = 3200.00m,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Italy",
                            EndDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/images/italy.jpg",
                            Notes = "A trip to explore the rich history and culture of Italy.",
                            StartDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed",
                            Title = "Cultural Escape",
                            UpdatedAt = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("59c5b94d-8015-48cd-bd86-0dbe486c4719")
                        },
                        new
                        {
                            Id = new Guid("172d5607-5dbd-4361-bf3f-fa76bfb84f70"),
                            Budget = 5000.00m,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Bahamas",
                            EndDate = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/images/bahamas.jpg",
                            Notes = "Escape to a private island in the Caribbean for rest and relaxation.",
                            StartDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Planned",
                            Title = "Tropical Retreat",
                            UpdatedAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("24fda663-5bf9-4e0d-8efd-111ae512dff5")
                        });
                });

            modelBuilder.Entity("OutTheGC.Models.TripInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("TripId");

                    b.ToTable("TripInvitations");
                });

            modelBuilder.Entity("OutTheGC.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0eaed767-eecd-4d19-a853-9da895e78057"),
                            Bio = "a ut erat id mauris vulputate elementumam varius.",
                            DateJoined = new DateTime(2017, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "britnaygore268@gmail.com",
                            FullName = "Britnay Gore",
                            ImageUrl = "",
                            Uid = ""
                        },
                        new
                        {
                            Id = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc"),
                            Bio = "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
                            DateJoined = new DateTime(2009, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "liz.paquette08@gmail.com",
                            FullName = "Liz Paquette",
                            ImageUrl = "",
                            Uid = ""
                        },
                        new
                        {
                            Id = new Guid("67a99b92-3485-4d39-8bce-33fe4fccfc85"),
                            Bio = "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
                            DateJoined = new DateTime(2006, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nigel.henry@gmail.com",
                            FullName = "Nigel Henry",
                            ImageUrl = "",
                            Uid = ""
                        },
                        new
                        {
                            Id = new Guid("59c5b94d-8015-48cd-bd86-0dbe486c4719"),
                            Bio = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
                            DateJoined = new DateTime(2008, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emariebroermann@gmail.com",
                            FullName = "Emma Broermann",
                            ImageUrl = "",
                            Uid = ""
                        },
                        new
                        {
                            Id = new Guid("24fda663-5bf9-4e0d-8efd-111ae512dff5"),
                            Bio = "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
                            DateJoined = new DateTime(2020, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "araya.west@rfsmart.com",
                            FullName = "Araya West",
                            ImageUrl = "",
                            Uid = ""
                        });
                });

            modelBuilder.Entity("OutTheGC.Models.UserTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTrips");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68840bbc-076e-437b-8f0a-c9216899fd91"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripId = new Guid("6f927882-1196-4d72-917d-972c6de3f1b4"),
                            UserId = new Guid("59c5b94d-8015-48cd-bd86-0dbe486c4719")
                        },
                        new
                        {
                            Id = new Guid("286be131-ea5a-4099-afa7-26db4efdd6eb"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripId = new Guid("6f927882-1196-4d72-917d-972c6de3f1b4"),
                            UserId = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc")
                        },
                        new
                        {
                            Id = new Guid("4918405d-c748-415c-9492-bc96a9aa02cd"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripId = new Guid("de59cf42-eb57-4045-b7bc-a578db398ad2"),
                            UserId = new Guid("0eaed767-eecd-4d19-a853-9da895e78057")
                        },
                        new
                        {
                            Id = new Guid("6522e40a-bac2-4567-908d-dcd071166cb8"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripId = new Guid("172d5607-5dbd-4361-bf3f-fa76bfb84f70"),
                            UserId = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc")
                        });
                });

            modelBuilder.Entity("OutTheGC.Models.UserVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersVotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58f3986c-2027-4a80-8559-87e669817032"),
                            ActivityId = new Guid("4a7cb92b-2b6a-4316-8bb0-402497c47bdb"),
                            UserId = new Guid("59c5b94d-8015-48cd-bd86-0dbe486c4719")
                        },
                        new
                        {
                            Id = new Guid("e7730dd4-0dbd-45ca-937a-3ff9af6ba29b"),
                            ActivityId = new Guid("175a8012-6200-4180-915b-f3e4d604923d"),
                            UserId = new Guid("59c5b94d-8015-48cd-bd86-0dbe486c4719")
                        },
                        new
                        {
                            Id = new Guid("4828ac00-f59d-4993-a5de-03eae2816b1f"),
                            ActivityId = new Guid("8d69e4e8-62b1-465d-bfc7-1a94c3d07a71"),
                            UserId = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc")
                        },
                        new
                        {
                            Id = new Guid("aaaca29b-657e-4b67-8fcf-68864cb1b07b"),
                            ActivityId = new Guid("64f3cda1-70cf-4b52-99b2-d9c60a5b5898"),
                            UserId = new Guid("8e98b8c4-6cf7-4817-b106-ffc59cbe83cc")
                        });
                });

            modelBuilder.Entity("OutTheGC.Models.Activity", b =>
                {
                    b.HasOne("OutTheGC.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutTheGC.Models.Trip", "Trip")
                        .WithMany("Activities")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutTheGC.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OutTheGC.Models.Comment", b =>
                {
                    b.HasOne("OutTheGC.Models.Activity", null)
                        .WithMany("Comments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutTheGC.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OutTheGC.Models.Trip", b =>
                {
                    b.HasOne("OutTheGC.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OutTheGC.Models.TripInvitation", b =>
                {
                    b.HasOne("OutTheGC.Models.User", null)
                        .WithMany("Invitations")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutTheGC.Models.Trip", "Trip")
                        .WithMany("SentInvitations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("OutTheGC.Models.UserTrip", b =>
                {
                    b.HasOne("OutTheGC.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutTheGC.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OutTheGC.Models.UserVote", b =>
                {
                    b.HasOne("OutTheGC.Models.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutTheGC.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OutTheGC.Models.Activity", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("OutTheGC.Models.Trip", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("SentInvitations");
                });

            modelBuilder.Entity("OutTheGC.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Comments");

                    b.Navigation("Invitations");
                });
#pragma warning restore 612, 618
        }
    }
}
